language: elixir
elixir:
- 1.2
otp_release:
- 18.0
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_12e0002f8980_key -iv $encrypted_12e0002f8980_iv
  -in .travis/whosinbot.pem.enc -out .travis/whosinbot.pem -d
after_success:
  - chmod 600 .travis/whosinbot.pem
  - mkdir -p ~/.ssh
  - cp .travis/whosinbot.pem ~/.ssh
  - cat .travis/host >> ~/.ssh/config
  - git remote add dokku dokku@colharris.com:whosinbot
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && git push dokku master
