---
apiVersion: v1
kind: ConfigMap
metadata:
  name: whos-in-bot-config
data:
  BOT_TOKEN: ""
  LOG_LEVEL: "debug"
  DB_USER: "whos_in_bot"
  DB_PASSWORD: ""
  DB_NAME: "whos_in_bot"
  DB_HOST: "apps-postgres-do-user-1557982-0.db.ondigitalocean.com"
  DB_PORT: "25060"
  DB_SSL: "true"
  DB_POOL_SIZE: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: whos-in-bot
spec:
  selector:
    app: whos-in-bot
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whos-in-bot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whos-in-bot
    spec:
      containers:
      - name: whos-in-bot
        image: colharris/whos_in_bot:f0e9764ee480a620792d4570e805e2c34386a50b
        ports:
        - containerPort: 5000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: whos-in-bot-config
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whos-in-bot
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - whosinbot.colharris.com
    secretName: whosinbot-prod-tls
  rules:
  - host: whosinbot.colharris.com
    http:
      paths:
      - backend:
          serviceName: whos-in-bot
          servicePort: 80